const FT = new FantasyTennis()
const SB = new ScoreBoard(FT)

FT.setUpTournament()
console.log(FT.theDraw1)
console.log(FT.theDraw2)
console.log(FT.theDraw3)
console.log(FT.theDraw4)
console.log(FT.theDraw5)
console.log(FT.theDraw6)
console.log(FT.theDraw7)
console.log(FT.theDraw8)
FT.randomizeStartingPlayers()
console.log(FT.theDraw1)
console.log(FT.theDraw2)
console.log(FT.theDraw3)
console.log(FT.theDraw4)
console.log(FT.theDraw5)
console.log(FT.theDraw6)
console.log(FT.theDraw7)
console.log(FT.theDraw8)
FT.mainLoop()
console.log(FT.theDraw1)
console.log(FT.theDraw2)
console.log(FT.theDraw3)
console.log(FT.theDraw4)
console.log(FT.theDraw5)
console.log(FT.theDraw6)
console.log(FT.theDraw7)
console.log(FT.theDraw8)